#!/usr/bin/env bash

set -e

SITE_ROOT="$(readlink -f "$(dirname "$0")/..")"
source $SITE_ROOT/bin/activate

echo "Installing pip packages"
pip install -r $SITE_ROOT/requirements.txt

echo "Running syncdb"
python $SITE_ROOT/cotracker/manage.py syncdb --noinput --no-initial-data

echo "If you need to create a superuser:"
echo "    $SITE_ROOT/bin/python $SITE_ROOT/cotracker/manage.py createsuperuser"

echo "Finished bootstrapping"
