#!/usr/bin/env bash

set -e

echo "Configuring CI environment for the test suite"

export DATABASE_URL=ignored
export SECRET_KEY=supersecretkey
export SENTRY_DSN=ignored
export EXPORT_PREFIX=ignored
SITE_ROOT="$(readlink -f "$(dirname "$0")/..")"

echo "DATABASE_URL:  $DATABASE_URL"
echo "SECRET_KEY:    $SECRET_KEY"
echo "SENTRY_DSN:    $SENTRY_DSN"
echo "EXPORT_PREFIX: $EXPORT_PREFIX"
echo "SITE_ROOT:     $SITE_ROOT"

echo "Installing pip packages for testing"
pip install -r $SITE_ROOT/requirements/development.txt

$SITE_ROOT/scripts/test
