#!/usr/bin/env bash

# Perform configuration setup to support a production environment.
# Usage: prep_production DOMAIN EXPORT_PREFIX

# Arguments:
#   DOMAIN          The domain at which this instance will be reachable
#   EXPORT_PREFIX   The prefix behind which to hide sensitive data

set -e
set -o pipefail

function die { echo $@; exit 1; }

DOMAIN=$1
EXPORT_PREFIX=$2
SITE_ROOT="$(readlink -f "$(dirname "$0")/..")"

[[ -z "$DOMAIN" ]] && die "Error: Please provide the DOMAIN for this instance"
[[ -z "$EXPORT_PREFIX" ]] && die "Error: Please provide the EXPORT_PREFIX for this instance"

echo "Installing dependencies"
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt-get install -y certbot python-certbot-nginx

echo "Fetching initial certificate"
sudo certbot certonly \
  --register-unsafely-without-email \
  --agree-tos \
  --nginx \
  -d $DOMAIN

NGINX=/etc/nginx/sites-enabled
echo "Updating nginx configuration to support HTTPS"
cat $SITE_ROOT/etc/nginx.secure \
    | sed "s@{{ site_root }}@$SITE_ROOT@g" \
    | sed "s@{{ domain_name }}@$DOMAIN@g" \
    | sed "s@{{ export_prefix }}@$EXPORT_PREFIX@g" \
    | sudo tee $NGINX/$DOMAIN

echo "Ensuring the blocking of unknown hosts covers HTTPS, too"
sudo cp $SITE_ROOT/etc/nginx.block_unknown_443 $NGINX/block_unknown
sudo service nginx reload

echo "Finished preparing for production"
