#!/bin/bash

# scripts/setup
# =============
# Set up application for the first time after cloning.
#
# !! Requires sudo
#
# Usage
# -----
# > scripts/setup [hosted domain] [Sentry DSN] [export prefix]
# e.g.
# > scripts/setup example.com https://access:key@sentry.example.com/2 ZYXWVUTSR
#
# Assumptions
# -----------
# - The app will be executed by a user named 'checkniner'
#

echo "===> Starting scripts/setup"

ALLOWED_HOSTS=$1
SENTRY_DSN=$2
EXPORT_PREFIX=$3
PG_DATABASE=checkniner
HOST_USER=checkniner
SECRET_KEY=$(python -c "import base64, os; print base64.b64encode(os.urandom(40))")
# Found this one-liner via http://stackoverflow.com/a/246128. Thanks!
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# The script dir is checkniner/scripts. The site root will be up one level.
SITE_ROOT="$(dirname "$SCRIPT_DIR")"
echo "     ALLOWED_HOSTS:     $ALLOWED_HOSTS"
echo "     SENTRY_DSN:        $SENTRY_DSN"
echo "     EXPORT_PREFIX:     $EXPORT_PREFIX"
echo "     PG_DATABASE:       $PG_DATABASE"
echo "     HOST_USER:         $HOST_USER"
echo "     SECRET_KEY:        $SECRET_KEY"
echo "     SITE_ROOT:         $SITE_ROOT"


echo "===> Setting locale"
# Postgres correctly insists on the locale being set properly
# Thanks to http://stackoverflow.com/a/17712701 for these!
locale-gen en_US en_US.UTF-8 
sudo dpkg-reconfigure locales


echo "===> Installing system packages"
PACKAGES="python-virtualenv python-dev postgresql libpq-dev nginx supervisor"
sudo apt-get install --assume-yes $PACKAGES


echo "===> Setting up postgres user & database"
# Developer Note: A couple of things to be aware of in this configuation:
# - We're using peer authentication, so we don't need a password or a hostname
# - This will work as long as django and the database are on the same host
# This initial 'cd /' avoids an error message caused by the postgres user
# attempting to navigate to the /root directory (the default directory for the
# root user) when 'sudo -u ...' is invoked.
cd /
sudo -u postgres bash -c "echo \"CREATE DATABASE $PG_DATABASE; CREATE USER $HOST_USER; GRANT ALL PRIVILEGES ON DATABASE $PG_DATABASE to $HOST_USER;\\q\" | psql"


echo "===> Updating supervisor configuration"
CONF_DIR=/etc/supervisor/conf.d
TEMPLATE_HOST_USER=ubuntu
sudo cp $SITE_ROOT/etc/supervisor.conf $CONF_DIR/checkniner.conf
sudo sed -i s@$TEMPLATE_HOST_USER@$HOST_USER@g $CONF_DIR/checkniner.conf
sudo service supervisor stop
sudo service supervisor start


# Setting up nginx & TLS certificates with Let's Encrypt on a fresh box is a
# bit complicated. First, because we don't have any certificates, we need to
# set up an unsecured configuration. Since the unsecured server answers Let's
# Encrypt's challenges to prove domain control, though, it must know about the
# /etc/letsencrypt/challenges directory and be able to alias into it.
#
# Once the unsecured nginx configuration is running, we can run our certify
# script to get real certificates. Finally, with those in possession, we can
# put the secured nginx configuration in place and do a final `nginx reload`.
#
# WARNING: If ALLOWED_HOSTS contains comma-seperated entries such as
# 'example.com,www.example.com' this section will not run correctly!

CONF_DIR=/etc/nginx
echo "===> Updating nginx configuration (unsecured)"
sudo rm $CONF_DIR/sites-enabled/default
sudo cp $SITE_ROOT/etc/nginx.unsecure $CONF_DIR/sites-available/checkniner
sudo ln -s $CONF_DIR/sites-available/checkniner $CONF_DIR/sites-enabled/checkniner
sudo sed -i "s@{{ site_root }}@$SITE_ROOT@g" $CONF_DIR/sites-enabled/checkniner
sudo sed -i "s/{{ domain_name }}/$ALLOWED_HOSTS/g" $CONF_DIR/sites-enabled/checkniner
sudo sed -i "s/{{ export_prefix }}/$EXPORT_PREFIX/g" $CONF_DIR/sites-enabled/checkniner

echo "===> Setting up TLS environment"
# To bring up the nginx conf, we're going to need the challenges directory to
# exist. Once it's up, we can run the certify.sh script to get everything else.
sudo mkdir -p /etc/letsencrypt/challenges
sudo service nginx restart

sudo cp $SITE_ROOT/scripts/certify.sh ~/certify.sh
echo "===> Getting TLS certificate"
sudo ~/certify.sh $ALLOWED_HOSTS

echo "===> Updating nginx configuration (secured)"
sudo cp $SITE_ROOT/etc/nginx.secure $CONF_DIR/sites-available/checkniner
sudo sed -i "s@{{ site_root }}@$SITE_ROOT@g" $CONF_DIR/sites-enabled/checkniner
sudo sed -i "s/{{ domain_name }}/$ALLOWED_HOSTS/g" $CONF_DIR/sites-enabled/checkniner
sudo sed -i "s/{{ export_prefix }}/$EXPORT_PREFIX/g" $CONF_DIR/sites-enabled/checkniner
sudo service nginx reload


echo "===> Creating virtualenv"
sudo -u $HOST_USER virtualenv $SITE_ROOT


echo "===> Setting env vars"
echo "export ALLOWED_HOSTS=$ALLOWED_HOSTS" >> $SITE_ROOT/bin/activate
echo "export DATABASE_URL=postgres://$HOST_USER@/$PG_DATABASE" >> $SITE_ROOT/bin/activate
echo "export DJANGO_SETTINGS_MODULE=cotracker.settings.production" >> $SITE_ROOT/bin/activate
echo "export PYTHONPATH=$SITE_ROOT/cotracker/" >> $SITE_ROOT/bin/activate
echo "export SECRET_KEY=$SECRET_KEY" >> $SITE_ROOT/bin/activate
echo "export SENTRY_DSN=$SENTRY_DSN" >> $SITE_ROOT/bin/activate
echo "export EXPORT_PREFIX=$EXPORT_PREFIX" >> $SITE_ROOT/bin/activate


echo "===> passing the baton to scripts/bootstrap"
sudo -u $HOST_USER $SITE_ROOT/scripts/bootstrap

echo "===> passing the baton to scripts/update"
sudo -u $HOST_USER $SITE_ROOT/scripts/update

echo "===> Everything is set up; Requesting supervisor to restart gunicorn"
sudo supervisorctl restart gunicorn

echo "===> setup completed"
