#!/bin/bash

set -e

function die { echo $@; exit 1; }

echo "Running the test suite"
[[ -x $(which coverage) ]] || die "Error: The dev dependencies are missing"

SITE_ROOT="$(readlink -f "$(dirname "$0")/..")"
cd $SITE_ROOT/cotracker/
coverage run manage.py test --settings=cotracker.settings.test
