#!/usr/bin/env bash

set -e

SITE_ROOT="$(readlink -f "$(dirname "$0")/..")"
source $SITE_ROOT/bin/activate
cd $SITE_ROOT/cotracker

echo "Performing migrations"
python manage.py migrate

echo "Running collectstatic"
python manage.py collectstatic --noinput

echo "Finished updating"
